const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    TOGGLE_CART_CHECK_HIDDEN: 'TOGGLE_CART_CHECK_HIDDEN',
    TOGGLE_CART_ADRESS_HIDDEN: 'TOGGLE_CART_ADRESS_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    PROMOCODE: 'PROMOCODE',
    PROMOCODE_ITEM: 'PROMOCODE_ITEM',
    PROMOCODE_ACCEPT: 'PROMOCODE_ACCEPT',
    CART_UPD: 'CART_UPD',
    MAIN_ORDER_MODAL: 'MAIN_ORDER_MODAL',
    MAIN_ORDER_MODAL_ITEM: 'MAIN_ORDER_MODAL_ITEM',
    GIFTS_SELECT:'GIFTS_SELECT',
    MAIN_MOTIV_MODAL: 'MAIN_MOTIV_MODAL',
    MOTIV: 'MOTIV'
  };
  
  export default CartActionTypes;
  