export const UserActionTypes = {
    TOGGLE_LOGIN_HIDDEN: 'TOGGLE_LOGIN_HIDDEN',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_ADRESS_ITEM: 'ADD_ADRESS_ITEM',
    TOGGLE_EDIT_NAME_HIDDEN: 'TOGGLE_EDIT_NAME_HIDDEN',
    TOGGLE_EDIT_EMAIL_HIDDEN: 'TOGGLE_EDIT_EMAIL_HIDDEN',
    SET_DARK: 'SET_DARK',
    SET_COOCK: 'SET_COOCK',
    TOGGLE_MENU_HIDDEN: 'TOGGLE_MENU_HIDDEN',
  };
  